config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/hello'

  resources :tips

   root 'welcome#hello'

end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
	belongs_to :reporter
	belongs_to :tip
end

app/models/reporter.rb
class Reporter < ActiveRecord::Base
	has_many :assignments
	has_many :tips, through: :assignments
end

app/models/tip.rb
class Tip < ActiveRecord::Base
	has_many :assignments
	has_many :reporters, through: :assignments

	accepts_nested_attributes_for :reporters
	
	validates :news_tip, :source, presence: {message: 'must not be blank'}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/tips_controller.rb
class TipsController < ApplicationController
  before_action :set_tip, only: [:show, :edit, :update, :destroy]

  # GET /tips
  # GET /tips.json
  def index
    @tips = Tip.all
  end

  # GET /tips/1
  # GET /tips/1.json
  def show
  end

  # GET /tips/new
  def new
    @tip = Tip.new
	@tip.reporters.build
  end

  # GET /tips/1/edit
  def edit
  end

  # POST /tips
  # POST /tips.json
  def create
    @tip = Tip.new(tip_params)

    respond_to do |format|
      if @tip.save
		EditorMailer.notification_email(self).deliver 
        format.html { redirect_to @tip, notice: 'Tip was successfully created.' }
        format.json { render :show, status: :created, location: @tip }
      else
        format.html { render :new }
        format.json { render json: @tip.errors, status: :unprocessable_entity }
      end
	  
	  
    end
  end

  # PATCH/PUT /tips/1
  # PATCH/PUT /tips/1.json
  def update
    respond_to do |format|
      if @tip.update(tip_params)
        format.html { redirect_to @tip, notice: 'Tip was successfully updated.' }
        format.json { render :show, status: :ok, location: @tip }
      else
        format.html { render :edit }
        format.json { render json: @tip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tips/1
  # DELETE /tips/1.json
  def destroy
    @tip.destroy
    respond_to do |format|
      format.html { redirect_to tips_url, notice: 'Tip was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tip
      @tip = Tip.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tip_params
      params.require(:tip).permit(:tip, :date, :source, reporter_ids: [], reporters_attributes: [:full_name])
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def hello
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tips_helper.rb
module TipsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tip Tracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div class="container">
	<div class="row">
		<div class="span9"> 	

	<% if user_signed_in? %>
	Logged in 
	<%= link_to 'Edit profile', edit_user_registration_path %> |
	<%= link_to "Logout", destroy_user_session_path, method: :delete %>
<%else %>
	<%= link_to "Sign up", new_user_registration_path %> |
	<%= link_to "Login", new_user_session_path %>
<% end %>

<%if notice %>
	<p class ="alert alert-success"><%= notice %></p>
<% end %>

<%if alert %>
	<p class ="alert alert-danger"><%= alert %></p>
<% end %> 	
		
		
		<%= yield %></div>
	
	

			
		</div>
	</div>
</div>
</body>
</html>

app/views/tips/_form.html.erb
<%= form_for @tip, :html => { :class => 'form-horizontal' } do |f| %>
  
  <div class="control-group">
    <%= f.label :tip, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :tip, :class => 'text_field' %>
    </div>
  </div>
  
  <div class="control-group">
    <%= f.label :date, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :date, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :source, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :source, :class => 'text_field' %>
    </div>
  </div>
  
   
  
  <p><h1> Reporter </h1>
  <%= f.fields_for :reporters do |reporter_form| %>
    <div class="field">
      <%= reporter_form.label :full_name %><br>
      <%= reporter_form.text_field :full_name %>
    </div>
  <% end %></p>
  <%= f.collection_select(:reporter_ids, Reporter.all, :id, :full_name, {selected: @tip.reporter_ids, include_blank: false},{ multiple: true }) %>
  <div class="actions">
  
  

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                tips_path, :class => 'btn' %>
  </div>
<% end %>

app/views/tips/edit.html.erb
<%- model_class = Tip -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/tips/index.html.erb
<%- model_class = Tip -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
	  <th><%= model_class.human_attribute_name(:tip) %></th>
	  <th><%= model_class.human_attribute_name(:date) %></th>
      <th><%= model_class.human_attribute_name(:source) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @tips.each do |tip| %>
      <tr>
        <td><%= link_to tip.id, tip_path(tip) %></td>
        <td><%= tip.tip %></td>
		<td><%= tip.date %></td>
        <td><%= tip.source %></td>
        <td><%=l tip.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_tip_path(tip), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      tip_path(tip),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_tip_path,
            :class => 'btn btn-primary' %>

app/views/tips/new.html.erb
<%- model_class = Tip -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/tips/show.html.erb
<%- model_class = Tip -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:date) %>:</strong></dt>
  <dd><%= @tip.date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:source) %>:</strong></dt>
  <dd><%= @tip.source %></dd>
  <dt><strong><%= model_class.human_attribute_name(:tip) %>:</strong></dt>
  <dd><%= @tip.tip %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              tips_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_tip_path(@tip), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              tip_path(@tip),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/welcome/hello.html.erb
<center>
<br /><br />
<br /><br />
<h1>Welcome to Tip Tracker</h1>

<br />
<br />

<p><%= link_to 'See all news tips', tips_path %>
<p><%= link_to 'Enter a tip', new_tip_path %>
</center>